# Generated by Django 4.1.3 on 2022-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_Pk", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("email", models.CharField(max_length=50)),
                ("is_staff", models.BooleanField()),
                ("is_admin", models.BooleanField()),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
