# Generated by Django 4.1.3 on 2022-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_Pk", models.IntegerField()),
                ("title", models.CharField(max_length=40)),
                ("login", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=100)),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                ("max_guest_count", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
