# Generated by Django 4.1.3 on 2022-12-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_events"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
        migrations.RemoveField(model_name="events", name="id_Pk",),
    ]
