# Generated by Django 4.1.3 on 2022-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
