# Generated by Django 4.1.3 on 2022-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_events_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
